main: nl.martenm.gameoflive.GameOfLive
name: GameOfLive
version: 1.0.0
author: MartenM
description: Game Of Live in minecraft!
commands:
  gameoflive:
    description: Game of live commands.
    aliases: gof