main: nl.martenm.gameoflive.GameOfLive
name: GameOfLife
version: 1.0.1
author: MartenM
description: Game Of Live in minecraft!
commands:
  gameoflife:
    description: Game of live commands.
    aliases: gol